language: cpp
branches:
  only:
    - master
cache:
    apt
before_install:
    - echo -e "Ubuntu version:"
    - lsb_release -sc
    - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
    - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - echo "yes" | sudo add-apt-repository ppa:boost-latest/ppa
    - sudo apt-get update -qq
install:
    - sudo apt-get install build-essential
    - sudo apt-get install -qq gcc-5 g++-5
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20 --slave /usr/bin/g++ g++ /usr/bin/g++-5
    - sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
    - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
    - sudo update-alternatives --set cc /usr/bin/gcc
    - sudo update-alternatives --set c++ /usr/bin/g++
    - sudo apt-get install -qq valgrind cppcheck git
    - sudo apt-get install -qq libsdl-dev libboost1.55-dev

before_script:
    - wget https://github.com/lonski/amarlon_dependencies/releases/download/1.0/amarlon-dep-linux64-1.0.tar.gz
    - tar -xvf amarlon-dep-linux64-1.0.tar.gz
    - ls lib include
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - LD_LIBRARY_PATH=../lib valgrind --error-exitcode=0 --track-origins=yes --leak-check=full ./ut_amarlon
    - cd -
    - cppcheck --enable=style -I . -f -q --std=c++11 ./src ./test

notifications:
  recipients:
    - lgromanowski+travis.ci@gmail.com
    - michal.lonski+travis.ci@gmail.com
  email:
    on_success: change
    on_failure: always
