// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: skill.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "skill.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace amarlon {

namespace {

const ::google::protobuf::Descriptor* SkillData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SkillData_reflection_ = NULL;
const ::google::protobuf::Descriptor* SkillsData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SkillsData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_skill_2eproto() {
  protobuf_AddDesc_skill_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "skill.proto");
  GOOGLE_CHECK(file != NULL);
  SkillData_descriptor_ = file->message_type(0);
  static const int SkillData_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, passive_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, range_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, radius_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, target_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, description_),
  };
  SkillData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SkillData_descriptor_,
      SkillData::default_instance_,
      SkillData_offsets_,
      -1,
      -1,
      -1,
      sizeof(SkillData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillData, _is_default_instance_));
  SkillsData_descriptor_ = file->message_type(1);
  static const int SkillsData_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillsData, skill_),
  };
  SkillsData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SkillsData_descriptor_,
      SkillsData::default_instance_,
      SkillsData_offsets_,
      -1,
      -1,
      -1,
      sizeof(SkillsData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillsData, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SkillsData, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_skill_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SkillData_descriptor_, &SkillData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SkillsData_descriptor_, &SkillsData::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_skill_2eproto() {
  delete SkillData::default_instance_;
  delete SkillData_reflection_;
  delete SkillsData::default_instance_;
  delete SkillsData_reflection_;
}

void protobuf_AddDesc_skill_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013skill.proto\022\007amarlon\"\216\001\n\tSkillData\022\n\n\002"
    "id\030\001 \001(\005\022\r\n\005level\030\002 \001(\005\022\017\n\007passive\030\003 \001(\010"
    "\022\r\n\005range\030\004 \001(\005\022\016\n\006radius\030\005 \001(\005\022\023\n\013targe"
    "t_type\030\006 \001(\005\022\014\n\004name\030\007 \001(\t\022\023\n\013descriptio"
    "n\030\010 \001(\t\"/\n\nSkillsData\022!\n\005skill\030\001 \003(\0132\022.a"
    "marlon.SkillDatab\006proto3", 224);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "skill.proto", &protobuf_RegisterTypes);
  SkillData::default_instance_ = new SkillData();
  SkillsData::default_instance_ = new SkillsData();
  SkillData::default_instance_->InitAsDefaultInstance();
  SkillsData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_skill_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_skill_2eproto {
  StaticDescriptorInitializer_skill_2eproto() {
    protobuf_AddDesc_skill_2eproto();
  }
} static_descriptor_initializer_skill_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SkillData::kIdFieldNumber;
const int SkillData::kLevelFieldNumber;
const int SkillData::kPassiveFieldNumber;
const int SkillData::kRangeFieldNumber;
const int SkillData::kRadiusFieldNumber;
const int SkillData::kTargetTypeFieldNumber;
const int SkillData::kNameFieldNumber;
const int SkillData::kDescriptionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SkillData::SkillData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:amarlon.SkillData)
}

void SkillData::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SkillData::SkillData(const SkillData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:amarlon.SkillData)
}

void SkillData::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0;
  level_ = 0;
  passive_ = false;
  range_ = 0;
  radius_ = 0;
  target_type_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SkillData::~SkillData() {
  // @@protoc_insertion_point(destructor:amarlon.SkillData)
  SharedDtor();
}

void SkillData::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void SkillData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SkillData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SkillData_descriptor_;
}

const SkillData& SkillData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_skill_2eproto();
  return *default_instance_;
}

SkillData* SkillData::default_instance_ = NULL;

SkillData* SkillData::New(::google::protobuf::Arena* arena) const {
  SkillData* n = new SkillData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SkillData::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<SkillData*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(id_, target_type_);
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool SkillData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:amarlon.SkillData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_level;
        break;
      }

      // optional int32 level = 2;
      case 2: {
        if (tag == 16) {
         parse_level:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &level_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_passive;
        break;
      }

      // optional bool passive = 3;
      case 3: {
        if (tag == 24) {
         parse_passive:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &passive_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_range;
        break;
      }

      // optional int32 range = 4;
      case 4: {
        if (tag == 32) {
         parse_range:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &range_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_radius;
        break;
      }

      // optional int32 radius = 5;
      case 5: {
        if (tag == 40) {
         parse_radius:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &radius_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_target_type;
        break;
      }

      // optional int32 target_type = 6;
      case 6: {
        if (tag == 48) {
         parse_target_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &target_type_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_name;
        break;
      }

      // optional string name = 7;
      case 7: {
        if (tag == 58) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "amarlon.SkillData.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_description;
        break;
      }

      // optional string description = 8;
      case 8: {
        if (tag == 66) {
         parse_description:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->description().data(), this->description().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "amarlon.SkillData.description"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:amarlon.SkillData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:amarlon.SkillData)
  return false;
#undef DO_
}

void SkillData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:amarlon.SkillData)
  // optional int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // optional int32 level = 2;
  if (this->level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->level(), output);
  }

  // optional bool passive = 3;
  if (this->passive() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->passive(), output);
  }

  // optional int32 range = 4;
  if (this->range() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->range(), output);
  }

  // optional int32 radius = 5;
  if (this->radius() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->radius(), output);
  }

  // optional int32 target_type = 6;
  if (this->target_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->target_type(), output);
  }

  // optional string name = 7;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "amarlon.SkillData.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->name(), output);
  }

  // optional string description = 8;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "amarlon.SkillData.description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->description(), output);
  }

  // @@protoc_insertion_point(serialize_end:amarlon.SkillData)
}

::google::protobuf::uint8* SkillData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:amarlon.SkillData)
  // optional int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // optional int32 level = 2;
  if (this->level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->level(), target);
  }

  // optional bool passive = 3;
  if (this->passive() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->passive(), target);
  }

  // optional int32 range = 4;
  if (this->range() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->range(), target);
  }

  // optional int32 radius = 5;
  if (this->radius() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->radius(), target);
  }

  // optional int32 target_type = 6;
  if (this->target_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->target_type(), target);
  }

  // optional string name = 7;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "amarlon.SkillData.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->name(), target);
  }

  // optional string description = 8;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "amarlon.SkillData.description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->description(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:amarlon.SkillData)
  return target;
}

int SkillData::ByteSize() const {
  int total_size = 0;

  // optional int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  // optional int32 level = 2;
  if (this->level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->level());
  }

  // optional bool passive = 3;
  if (this->passive() != 0) {
    total_size += 1 + 1;
  }

  // optional int32 range = 4;
  if (this->range() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->range());
  }

  // optional int32 radius = 5;
  if (this->radius() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->radius());
  }

  // optional int32 target_type = 6;
  if (this->target_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->target_type());
  }

  // optional string name = 7;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional string description = 8;
  if (this->description().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->description());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SkillData::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SkillData* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SkillData>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SkillData::MergeFrom(const SkillData& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.level() != 0) {
    set_level(from.level());
  }
  if (from.passive() != 0) {
    set_passive(from.passive());
  }
  if (from.range() != 0) {
    set_range(from.range());
  }
  if (from.radius() != 0) {
    set_radius(from.radius());
  }
  if (from.target_type() != 0) {
    set_target_type(from.target_type());
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.description().size() > 0) {

    description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
  }
}

void SkillData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SkillData::CopyFrom(const SkillData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SkillData::IsInitialized() const {

  return true;
}

void SkillData::Swap(SkillData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SkillData::InternalSwap(SkillData* other) {
  std::swap(id_, other->id_);
  std::swap(level_, other->level_);
  std::swap(passive_, other->passive_);
  std::swap(range_, other->range_);
  std::swap(radius_, other->radius_);
  std::swap(target_type_, other->target_type_);
  name_.Swap(&other->name_);
  description_.Swap(&other->description_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SkillData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SkillData_descriptor_;
  metadata.reflection = SkillData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SkillData

// optional int32 id = 1;
void SkillData::clear_id() {
  id_ = 0;
}
 ::google::protobuf::int32 SkillData::id() const {
  // @@protoc_insertion_point(field_get:amarlon.SkillData.id)
  return id_;
}
 void SkillData::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SkillData.id)
}

// optional int32 level = 2;
void SkillData::clear_level() {
  level_ = 0;
}
 ::google::protobuf::int32 SkillData::level() const {
  // @@protoc_insertion_point(field_get:amarlon.SkillData.level)
  return level_;
}
 void SkillData::set_level(::google::protobuf::int32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SkillData.level)
}

// optional bool passive = 3;
void SkillData::clear_passive() {
  passive_ = false;
}
 bool SkillData::passive() const {
  // @@protoc_insertion_point(field_get:amarlon.SkillData.passive)
  return passive_;
}
 void SkillData::set_passive(bool value) {
  
  passive_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SkillData.passive)
}

// optional int32 range = 4;
void SkillData::clear_range() {
  range_ = 0;
}
 ::google::protobuf::int32 SkillData::range() const {
  // @@protoc_insertion_point(field_get:amarlon.SkillData.range)
  return range_;
}
 void SkillData::set_range(::google::protobuf::int32 value) {
  
  range_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SkillData.range)
}

// optional int32 radius = 5;
void SkillData::clear_radius() {
  radius_ = 0;
}
 ::google::protobuf::int32 SkillData::radius() const {
  // @@protoc_insertion_point(field_get:amarlon.SkillData.radius)
  return radius_;
}
 void SkillData::set_radius(::google::protobuf::int32 value) {
  
  radius_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SkillData.radius)
}

// optional int32 target_type = 6;
void SkillData::clear_target_type() {
  target_type_ = 0;
}
 ::google::protobuf::int32 SkillData::target_type() const {
  // @@protoc_insertion_point(field_get:amarlon.SkillData.target_type)
  return target_type_;
}
 void SkillData::set_target_type(::google::protobuf::int32 value) {
  
  target_type_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SkillData.target_type)
}

// optional string name = 7;
void SkillData::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& SkillData::name() const {
  // @@protoc_insertion_point(field_get:amarlon.SkillData.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SkillData::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:amarlon.SkillData.name)
}
 void SkillData::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:amarlon.SkillData.name)
}
 void SkillData::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:amarlon.SkillData.name)
}
 ::std::string* SkillData::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:amarlon.SkillData.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* SkillData::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SkillData::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:amarlon.SkillData.name)
}

// optional string description = 8;
void SkillData::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& SkillData::description() const {
  // @@protoc_insertion_point(field_get:amarlon.SkillData.description)
  return description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SkillData::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:amarlon.SkillData.description)
}
 void SkillData::set_description(const char* value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:amarlon.SkillData.description)
}
 void SkillData::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:amarlon.SkillData.description)
}
 ::std::string* SkillData::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:amarlon.SkillData.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* SkillData::release_description() {
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SkillData::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:amarlon.SkillData.description)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SkillsData::kSkillFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SkillsData::SkillsData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:amarlon.SkillsData)
}

void SkillsData::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SkillsData::SkillsData(const SkillsData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:amarlon.SkillsData)
}

void SkillsData::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

SkillsData::~SkillsData() {
  // @@protoc_insertion_point(destructor:amarlon.SkillsData)
  SharedDtor();
}

void SkillsData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SkillsData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SkillsData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SkillsData_descriptor_;
}

const SkillsData& SkillsData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_skill_2eproto();
  return *default_instance_;
}

SkillsData* SkillsData::default_instance_ = NULL;

SkillsData* SkillsData::New(::google::protobuf::Arena* arena) const {
  SkillsData* n = new SkillsData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SkillsData::Clear() {
  skill_.Clear();
}

bool SkillsData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:amarlon.SkillsData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .amarlon.SkillData skill = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_skill:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_skill()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_skill;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:amarlon.SkillsData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:amarlon.SkillsData)
  return false;
#undef DO_
}

void SkillsData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:amarlon.SkillsData)
  // repeated .amarlon.SkillData skill = 1;
  for (unsigned int i = 0, n = this->skill_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->skill(i), output);
  }

  // @@protoc_insertion_point(serialize_end:amarlon.SkillsData)
}

::google::protobuf::uint8* SkillsData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:amarlon.SkillsData)
  // repeated .amarlon.SkillData skill = 1;
  for (unsigned int i = 0, n = this->skill_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->skill(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:amarlon.SkillsData)
  return target;
}

int SkillsData::ByteSize() const {
  int total_size = 0;

  // repeated .amarlon.SkillData skill = 1;
  total_size += 1 * this->skill_size();
  for (int i = 0; i < this->skill_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->skill(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SkillsData::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SkillsData* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SkillsData>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SkillsData::MergeFrom(const SkillsData& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  skill_.MergeFrom(from.skill_);
}

void SkillsData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SkillsData::CopyFrom(const SkillsData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SkillsData::IsInitialized() const {

  return true;
}

void SkillsData::Swap(SkillsData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SkillsData::InternalSwap(SkillsData* other) {
  skill_.UnsafeArenaSwap(&other->skill_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SkillsData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SkillsData_descriptor_;
  metadata.reflection = SkillsData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SkillsData

// repeated .amarlon.SkillData skill = 1;
int SkillsData::skill_size() const {
  return skill_.size();
}
void SkillsData::clear_skill() {
  skill_.Clear();
}
const ::amarlon::SkillData& SkillsData::skill(int index) const {
  // @@protoc_insertion_point(field_get:amarlon.SkillsData.skill)
  return skill_.Get(index);
}
::amarlon::SkillData* SkillsData::mutable_skill(int index) {
  // @@protoc_insertion_point(field_mutable:amarlon.SkillsData.skill)
  return skill_.Mutable(index);
}
::amarlon::SkillData* SkillsData::add_skill() {
  // @@protoc_insertion_point(field_add:amarlon.SkillsData.skill)
  return skill_.Add();
}
::google::protobuf::RepeatedPtrField< ::amarlon::SkillData >*
SkillsData::mutable_skill() {
  // @@protoc_insertion_point(field_mutable_list:amarlon.SkillsData.skill)
  return &skill_;
}
const ::google::protobuf::RepeatedPtrField< ::amarlon::SkillData >&
SkillsData::skill() const {
  // @@protoc_insertion_point(field_list:amarlon.SkillsData.skill)
  return skill_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace amarlon

// @@protoc_insertion_point(global_scope)
