// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spell.proto

#ifndef PROTOBUF_spell_2eproto__INCLUDED
#define PROTOBUF_spell_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace amarlon {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_spell_2eproto();
void protobuf_AssignDesc_spell_2eproto();
void protobuf_ShutdownFile_spell_2eproto();

class SpellData;
class SpellsData;

// ===================================================================

class SpellData : public ::google::protobuf::Message {
 public:
  SpellData();
  virtual ~SpellData();

  SpellData(const SpellData& from);

  inline SpellData& operator=(const SpellData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpellData& default_instance();

  void Swap(SpellData* other);

  // implements Message ----------------------------------------------

  inline SpellData* New() const { return New(NULL); }

  SpellData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SpellData& from);
  void MergeFrom(const SpellData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SpellData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // required int32 level = 2;
  bool has_level() const;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // required int32 char_class = 3;
  bool has_char_class() const;
  void clear_char_class();
  static const int kCharClassFieldNumber = 3;
  ::google::protobuf::int32 char_class() const;
  void set_char_class(::google::protobuf::int32 value);

  // required int32 target_type = 4;
  bool has_target_type() const;
  void clear_target_type();
  static const int kTargetTypeFieldNumber = 4;
  ::google::protobuf::int32 target_type() const;
  void set_target_type(::google::protobuf::int32 value);

  // required string name = 5;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 5;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required string description = 6;
  bool has_description() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 6;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // optional bool passive = 7 [default = false];
  bool has_passive() const;
  void clear_passive();
  static const int kPassiveFieldNumber = 7;
  bool passive() const;
  void set_passive(bool value);

  // optional int32 radius = 8 [default = 0];
  bool has_radius() const;
  void clear_radius();
  static const int kRadiusFieldNumber = 8;
  ::google::protobuf::int32 radius() const;
  void set_radius(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:amarlon.SpellData)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_char_class();
  inline void clear_has_char_class();
  inline void set_has_target_type();
  inline void clear_has_target_type();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_description();
  inline void clear_has_description();
  inline void set_has_passive();
  inline void clear_has_passive();
  inline void set_has_radius();
  inline void clear_has_radius();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 char_class_;
  ::google::protobuf::int32 target_type_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  bool passive_;
  ::google::protobuf::int32 radius_;
  friend void  protobuf_AddDesc_spell_2eproto();
  friend void protobuf_AssignDesc_spell_2eproto();
  friend void protobuf_ShutdownFile_spell_2eproto();

  void InitAsDefaultInstance();
  static SpellData* default_instance_;
};
// -------------------------------------------------------------------

class SpellsData : public ::google::protobuf::Message {
 public:
  SpellsData();
  virtual ~SpellsData();

  SpellsData(const SpellsData& from);

  inline SpellsData& operator=(const SpellsData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpellsData& default_instance();

  void Swap(SpellsData* other);

  // implements Message ----------------------------------------------

  inline SpellsData* New() const { return New(NULL); }

  SpellsData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SpellsData& from);
  void MergeFrom(const SpellsData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SpellsData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .amarlon.SpellData spell = 1;
  int spell_size() const;
  void clear_spell();
  static const int kSpellFieldNumber = 1;
  const ::amarlon::SpellData& spell(int index) const;
  ::amarlon::SpellData* mutable_spell(int index);
  ::amarlon::SpellData* add_spell();
  ::google::protobuf::RepeatedPtrField< ::amarlon::SpellData >*
      mutable_spell();
  const ::google::protobuf::RepeatedPtrField< ::amarlon::SpellData >&
      spell() const;

  // @@protoc_insertion_point(class_scope:amarlon.SpellsData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::amarlon::SpellData > spell_;
  friend void  protobuf_AddDesc_spell_2eproto();
  friend void protobuf_AssignDesc_spell_2eproto();
  friend void protobuf_ShutdownFile_spell_2eproto();

  void InitAsDefaultInstance();
  static SpellsData* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SpellData

// required int32 id = 1;
inline bool SpellData::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SpellData::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SpellData::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SpellData::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 SpellData::id() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.id)
  return id_;
}
inline void SpellData::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.id)
}

// required int32 level = 2;
inline bool SpellData::has_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SpellData::set_has_level() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SpellData::clear_has_level() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SpellData::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 SpellData::level() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.level)
  return level_;
}
inline void SpellData::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.level)
}

// required int32 char_class = 3;
inline bool SpellData::has_char_class() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SpellData::set_has_char_class() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SpellData::clear_has_char_class() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SpellData::clear_char_class() {
  char_class_ = 0;
  clear_has_char_class();
}
inline ::google::protobuf::int32 SpellData::char_class() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.char_class)
  return char_class_;
}
inline void SpellData::set_char_class(::google::protobuf::int32 value) {
  set_has_char_class();
  char_class_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.char_class)
}

// required int32 target_type = 4;
inline bool SpellData::has_target_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SpellData::set_has_target_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SpellData::clear_has_target_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SpellData::clear_target_type() {
  target_type_ = 0;
  clear_has_target_type();
}
inline ::google::protobuf::int32 SpellData::target_type() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.target_type)
  return target_type_;
}
inline void SpellData::set_target_type(::google::protobuf::int32 value) {
  set_has_target_type();
  target_type_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.target_type)
}

// required string name = 5;
inline bool SpellData::has_name() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SpellData::set_has_name() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SpellData::clear_has_name() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SpellData::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& SpellData::name() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpellData::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:amarlon.SpellData.name)
}
inline void SpellData::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:amarlon.SpellData.name)
}
inline void SpellData::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:amarlon.SpellData.name)
}
inline ::std::string* SpellData::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:amarlon.SpellData.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SpellData::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpellData::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:amarlon.SpellData.name)
}

// required string description = 6;
inline bool SpellData::has_description() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SpellData::set_has_description() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SpellData::clear_has_description() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SpellData::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_description();
}
inline const ::std::string& SpellData::description() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.description)
  return description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpellData::set_description(const ::std::string& value) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:amarlon.SpellData.description)
}
inline void SpellData::set_description(const char* value) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:amarlon.SpellData.description)
}
inline void SpellData::set_description(const char* value, size_t size) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:amarlon.SpellData.description)
}
inline ::std::string* SpellData::mutable_description() {
  set_has_description();
  // @@protoc_insertion_point(field_mutable:amarlon.SpellData.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SpellData::release_description() {
  clear_has_description();
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpellData::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    set_has_description();
  } else {
    clear_has_description();
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:amarlon.SpellData.description)
}

// optional bool passive = 7 [default = false];
inline bool SpellData::has_passive() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SpellData::set_has_passive() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SpellData::clear_has_passive() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SpellData::clear_passive() {
  passive_ = false;
  clear_has_passive();
}
inline bool SpellData::passive() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.passive)
  return passive_;
}
inline void SpellData::set_passive(bool value) {
  set_has_passive();
  passive_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.passive)
}

// optional int32 radius = 8 [default = 0];
inline bool SpellData::has_radius() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void SpellData::set_has_radius() {
  _has_bits_[0] |= 0x00000080u;
}
inline void SpellData::clear_has_radius() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void SpellData::clear_radius() {
  radius_ = 0;
  clear_has_radius();
}
inline ::google::protobuf::int32 SpellData::radius() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.radius)
  return radius_;
}
inline void SpellData::set_radius(::google::protobuf::int32 value) {
  set_has_radius();
  radius_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.radius)
}

// -------------------------------------------------------------------

// SpellsData

// repeated .amarlon.SpellData spell = 1;
inline int SpellsData::spell_size() const {
  return spell_.size();
}
inline void SpellsData::clear_spell() {
  spell_.Clear();
}
inline const ::amarlon::SpellData& SpellsData::spell(int index) const {
  // @@protoc_insertion_point(field_get:amarlon.SpellsData.spell)
  return spell_.Get(index);
}
inline ::amarlon::SpellData* SpellsData::mutable_spell(int index) {
  // @@protoc_insertion_point(field_mutable:amarlon.SpellsData.spell)
  return spell_.Mutable(index);
}
inline ::amarlon::SpellData* SpellsData::add_spell() {
  // @@protoc_insertion_point(field_add:amarlon.SpellsData.spell)
  return spell_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::amarlon::SpellData >*
SpellsData::mutable_spell() {
  // @@protoc_insertion_point(field_mutable_list:amarlon.SpellsData.spell)
  return &spell_;
}
inline const ::google::protobuf::RepeatedPtrField< ::amarlon::SpellData >&
SpellsData::spell() const {
  // @@protoc_insertion_point(field_list:amarlon.SpellsData.spell)
  return spell_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace amarlon

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_spell_2eproto__INCLUDED
