// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spell.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "spell.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace amarlon {

namespace {

const ::google::protobuf::Descriptor* SpellData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpellData_reflection_ = NULL;
const ::google::protobuf::Descriptor* SpellsData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpellsData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_spell_2eproto() {
  protobuf_AddDesc_spell_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "spell.proto");
  GOOGLE_CHECK(file != NULL);
  SpellData_descriptor_ = file->message_type(0);
  static const int SpellData_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, char_class_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, target_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, description_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, passive_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, radius_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, range_),
  };
  SpellData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SpellData_descriptor_,
      SpellData::default_instance_,
      SpellData_offsets_,
      -1,
      -1,
      -1,
      sizeof(SpellData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellData, _is_default_instance_));
  SpellsData_descriptor_ = file->message_type(1);
  static const int SpellsData_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellsData, spell_),
  };
  SpellsData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SpellsData_descriptor_,
      SpellsData::default_instance_,
      SpellsData_offsets_,
      -1,
      -1,
      -1,
      sizeof(SpellsData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellsData, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpellsData, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_spell_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SpellData_descriptor_, &SpellData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SpellsData_descriptor_, &SpellsData::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_spell_2eproto() {
  delete SpellData::default_instance_;
  delete SpellData_reflection_;
  delete SpellsData::default_instance_;
  delete SpellsData_reflection_;
}

void protobuf_AddDesc_spell_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013spell.proto\022\007amarlon\"\242\001\n\tSpellData\022\n\n\002"
    "id\030\001 \001(\005\022\r\n\005level\030\002 \001(\005\022\022\n\nchar_class\030\003 "
    "\001(\005\022\023\n\013target_type\030\004 \001(\005\022\014\n\004name\030\005 \001(\t\022\023"
    "\n\013description\030\006 \001(\t\022\017\n\007passive\030\007 \001(\010\022\016\n\006"
    "radius\030\010 \001(\005\022\r\n\005range\030\t \001(\005\"/\n\nSpellsDat"
    "a\022!\n\005spell\030\001 \003(\0132\022.amarlon.SpellDatab\006pr"
    "oto3", 244);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "spell.proto", &protobuf_RegisterTypes);
  SpellData::default_instance_ = new SpellData();
  SpellsData::default_instance_ = new SpellsData();
  SpellData::default_instance_->InitAsDefaultInstance();
  SpellsData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_spell_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_spell_2eproto {
  StaticDescriptorInitializer_spell_2eproto() {
    protobuf_AddDesc_spell_2eproto();
  }
} static_descriptor_initializer_spell_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpellData::kIdFieldNumber;
const int SpellData::kLevelFieldNumber;
const int SpellData::kCharClassFieldNumber;
const int SpellData::kTargetTypeFieldNumber;
const int SpellData::kNameFieldNumber;
const int SpellData::kDescriptionFieldNumber;
const int SpellData::kPassiveFieldNumber;
const int SpellData::kRadiusFieldNumber;
const int SpellData::kRangeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpellData::SpellData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:amarlon.SpellData)
}

void SpellData::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SpellData::SpellData(const SpellData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:amarlon.SpellData)
}

void SpellData::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0;
  level_ = 0;
  char_class_ = 0;
  target_type_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  passive_ = false;
  radius_ = 0;
  range_ = 0;
}

SpellData::~SpellData() {
  // @@protoc_insertion_point(destructor:amarlon.SpellData)
  SharedDtor();
}

void SpellData::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void SpellData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpellData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpellData_descriptor_;
}

const SpellData& SpellData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_spell_2eproto();
  return *default_instance_;
}

SpellData* SpellData::default_instance_ = NULL;

SpellData* SpellData::New(::google::protobuf::Arena* arena) const {
  SpellData* n = new SpellData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SpellData::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<SpellData*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(id_, target_type_);
  ZR_(passive_, radius_);
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  range_ = 0;

#undef ZR_HELPER_
#undef ZR_

}

bool SpellData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:amarlon.SpellData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_level;
        break;
      }

      // optional int32 level = 2;
      case 2: {
        if (tag == 16) {
         parse_level:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &level_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_char_class;
        break;
      }

      // optional int32 char_class = 3;
      case 3: {
        if (tag == 24) {
         parse_char_class:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &char_class_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_target_type;
        break;
      }

      // optional int32 target_type = 4;
      case 4: {
        if (tag == 32) {
         parse_target_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &target_type_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_name;
        break;
      }

      // optional string name = 5;
      case 5: {
        if (tag == 42) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "amarlon.SpellData.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_description;
        break;
      }

      // optional string description = 6;
      case 6: {
        if (tag == 50) {
         parse_description:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->description().data(), this->description().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "amarlon.SpellData.description"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_passive;
        break;
      }

      // optional bool passive = 7;
      case 7: {
        if (tag == 56) {
         parse_passive:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &passive_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_radius;
        break;
      }

      // optional int32 radius = 8;
      case 8: {
        if (tag == 64) {
         parse_radius:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &radius_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_range;
        break;
      }

      // optional int32 range = 9;
      case 9: {
        if (tag == 72) {
         parse_range:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &range_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:amarlon.SpellData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:amarlon.SpellData)
  return false;
#undef DO_
}

void SpellData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:amarlon.SpellData)
  // optional int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // optional int32 level = 2;
  if (this->level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->level(), output);
  }

  // optional int32 char_class = 3;
  if (this->char_class() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->char_class(), output);
  }

  // optional int32 target_type = 4;
  if (this->target_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->target_type(), output);
  }

  // optional string name = 5;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "amarlon.SpellData.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->name(), output);
  }

  // optional string description = 6;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "amarlon.SpellData.description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->description(), output);
  }

  // optional bool passive = 7;
  if (this->passive() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->passive(), output);
  }

  // optional int32 radius = 8;
  if (this->radius() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->radius(), output);
  }

  // optional int32 range = 9;
  if (this->range() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->range(), output);
  }

  // @@protoc_insertion_point(serialize_end:amarlon.SpellData)
}

::google::protobuf::uint8* SpellData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:amarlon.SpellData)
  // optional int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // optional int32 level = 2;
  if (this->level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->level(), target);
  }

  // optional int32 char_class = 3;
  if (this->char_class() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->char_class(), target);
  }

  // optional int32 target_type = 4;
  if (this->target_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->target_type(), target);
  }

  // optional string name = 5;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "amarlon.SpellData.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->name(), target);
  }

  // optional string description = 6;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "amarlon.SpellData.description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->description(), target);
  }

  // optional bool passive = 7;
  if (this->passive() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->passive(), target);
  }

  // optional int32 radius = 8;
  if (this->radius() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->radius(), target);
  }

  // optional int32 range = 9;
  if (this->range() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->range(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:amarlon.SpellData)
  return target;
}

int SpellData::ByteSize() const {
  int total_size = 0;

  // optional int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  // optional int32 level = 2;
  if (this->level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->level());
  }

  // optional int32 char_class = 3;
  if (this->char_class() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->char_class());
  }

  // optional int32 target_type = 4;
  if (this->target_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->target_type());
  }

  // optional string name = 5;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional string description = 6;
  if (this->description().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->description());
  }

  // optional bool passive = 7;
  if (this->passive() != 0) {
    total_size += 1 + 1;
  }

  // optional int32 radius = 8;
  if (this->radius() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->radius());
  }

  // optional int32 range = 9;
  if (this->range() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->range());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpellData::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SpellData* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SpellData>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SpellData::MergeFrom(const SpellData& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.level() != 0) {
    set_level(from.level());
  }
  if (from.char_class() != 0) {
    set_char_class(from.char_class());
  }
  if (from.target_type() != 0) {
    set_target_type(from.target_type());
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.description().size() > 0) {

    description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
  }
  if (from.passive() != 0) {
    set_passive(from.passive());
  }
  if (from.radius() != 0) {
    set_radius(from.radius());
  }
  if (from.range() != 0) {
    set_range(from.range());
  }
}

void SpellData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpellData::CopyFrom(const SpellData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpellData::IsInitialized() const {

  return true;
}

void SpellData::Swap(SpellData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpellData::InternalSwap(SpellData* other) {
  std::swap(id_, other->id_);
  std::swap(level_, other->level_);
  std::swap(char_class_, other->char_class_);
  std::swap(target_type_, other->target_type_);
  name_.Swap(&other->name_);
  description_.Swap(&other->description_);
  std::swap(passive_, other->passive_);
  std::swap(radius_, other->radius_);
  std::swap(range_, other->range_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SpellData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpellData_descriptor_;
  metadata.reflection = SpellData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SpellData

// optional int32 id = 1;
void SpellData::clear_id() {
  id_ = 0;
}
 ::google::protobuf::int32 SpellData::id() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.id)
  return id_;
}
 void SpellData::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.id)
}

// optional int32 level = 2;
void SpellData::clear_level() {
  level_ = 0;
}
 ::google::protobuf::int32 SpellData::level() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.level)
  return level_;
}
 void SpellData::set_level(::google::protobuf::int32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.level)
}

// optional int32 char_class = 3;
void SpellData::clear_char_class() {
  char_class_ = 0;
}
 ::google::protobuf::int32 SpellData::char_class() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.char_class)
  return char_class_;
}
 void SpellData::set_char_class(::google::protobuf::int32 value) {
  
  char_class_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.char_class)
}

// optional int32 target_type = 4;
void SpellData::clear_target_type() {
  target_type_ = 0;
}
 ::google::protobuf::int32 SpellData::target_type() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.target_type)
  return target_type_;
}
 void SpellData::set_target_type(::google::protobuf::int32 value) {
  
  target_type_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.target_type)
}

// optional string name = 5;
void SpellData::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& SpellData::name() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SpellData::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:amarlon.SpellData.name)
}
 void SpellData::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:amarlon.SpellData.name)
}
 void SpellData::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:amarlon.SpellData.name)
}
 ::std::string* SpellData::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:amarlon.SpellData.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* SpellData::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SpellData::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:amarlon.SpellData.name)
}

// optional string description = 6;
void SpellData::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& SpellData::description() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.description)
  return description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SpellData::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:amarlon.SpellData.description)
}
 void SpellData::set_description(const char* value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:amarlon.SpellData.description)
}
 void SpellData::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:amarlon.SpellData.description)
}
 ::std::string* SpellData::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:amarlon.SpellData.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* SpellData::release_description() {
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SpellData::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:amarlon.SpellData.description)
}

// optional bool passive = 7;
void SpellData::clear_passive() {
  passive_ = false;
}
 bool SpellData::passive() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.passive)
  return passive_;
}
 void SpellData::set_passive(bool value) {
  
  passive_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.passive)
}

// optional int32 radius = 8;
void SpellData::clear_radius() {
  radius_ = 0;
}
 ::google::protobuf::int32 SpellData::radius() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.radius)
  return radius_;
}
 void SpellData::set_radius(::google::protobuf::int32 value) {
  
  radius_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.radius)
}

// optional int32 range = 9;
void SpellData::clear_range() {
  range_ = 0;
}
 ::google::protobuf::int32 SpellData::range() const {
  // @@protoc_insertion_point(field_get:amarlon.SpellData.range)
  return range_;
}
 void SpellData::set_range(::google::protobuf::int32 value) {
  
  range_ = value;
  // @@protoc_insertion_point(field_set:amarlon.SpellData.range)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpellsData::kSpellFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpellsData::SpellsData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:amarlon.SpellsData)
}

void SpellsData::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SpellsData::SpellsData(const SpellsData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:amarlon.SpellsData)
}

void SpellsData::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

SpellsData::~SpellsData() {
  // @@protoc_insertion_point(destructor:amarlon.SpellsData)
  SharedDtor();
}

void SpellsData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SpellsData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpellsData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpellsData_descriptor_;
}

const SpellsData& SpellsData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_spell_2eproto();
  return *default_instance_;
}

SpellsData* SpellsData::default_instance_ = NULL;

SpellsData* SpellsData::New(::google::protobuf::Arena* arena) const {
  SpellsData* n = new SpellsData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SpellsData::Clear() {
  spell_.Clear();
}

bool SpellsData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:amarlon.SpellsData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .amarlon.SpellData spell = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_spell:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_spell()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_spell;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:amarlon.SpellsData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:amarlon.SpellsData)
  return false;
#undef DO_
}

void SpellsData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:amarlon.SpellsData)
  // repeated .amarlon.SpellData spell = 1;
  for (unsigned int i = 0, n = this->spell_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->spell(i), output);
  }

  // @@protoc_insertion_point(serialize_end:amarlon.SpellsData)
}

::google::protobuf::uint8* SpellsData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:amarlon.SpellsData)
  // repeated .amarlon.SpellData spell = 1;
  for (unsigned int i = 0, n = this->spell_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->spell(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:amarlon.SpellsData)
  return target;
}

int SpellsData::ByteSize() const {
  int total_size = 0;

  // repeated .amarlon.SpellData spell = 1;
  total_size += 1 * this->spell_size();
  for (int i = 0; i < this->spell_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->spell(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpellsData::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SpellsData* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SpellsData>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SpellsData::MergeFrom(const SpellsData& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  spell_.MergeFrom(from.spell_);
}

void SpellsData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpellsData::CopyFrom(const SpellsData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpellsData::IsInitialized() const {

  return true;
}

void SpellsData::Swap(SpellsData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpellsData::InternalSwap(SpellsData* other) {
  spell_.UnsafeArenaSwap(&other->spell_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SpellsData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpellsData_descriptor_;
  metadata.reflection = SpellsData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SpellsData

// repeated .amarlon.SpellData spell = 1;
int SpellsData::spell_size() const {
  return spell_.size();
}
void SpellsData::clear_spell() {
  spell_.Clear();
}
const ::amarlon::SpellData& SpellsData::spell(int index) const {
  // @@protoc_insertion_point(field_get:amarlon.SpellsData.spell)
  return spell_.Get(index);
}
::amarlon::SpellData* SpellsData::mutable_spell(int index) {
  // @@protoc_insertion_point(field_mutable:amarlon.SpellsData.spell)
  return spell_.Mutable(index);
}
::amarlon::SpellData* SpellsData::add_spell() {
  // @@protoc_insertion_point(field_add:amarlon.SpellsData.spell)
  return spell_.Add();
}
::google::protobuf::RepeatedPtrField< ::amarlon::SpellData >*
SpellsData::mutable_spell() {
  // @@protoc_insertion_point(field_mutable_list:amarlon.SpellsData.spell)
  return &spell_;
}
const ::google::protobuf::RepeatedPtrField< ::amarlon::SpellData >&
SpellsData::spell() const {
  // @@protoc_insertion_point(field_list:amarlon.SpellsData.spell)
  return spell_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace amarlon

// @@protoc_insertion_point(global_scope)
