// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: utils.proto

#ifndef PROTOBUF_utils_2eproto__INCLUDED
#define PROTOBUF_utils_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace amarlon {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_utils_2eproto();
void protobuf_AssignDesc_utils_2eproto();
void protobuf_ShutdownFile_utils_2eproto();

class IntIntPair;

// ===================================================================

class IntIntPair : public ::google::protobuf::Message {
 public:
  IntIntPair();
  virtual ~IntIntPair();

  IntIntPair(const IntIntPair& from);

  inline IntIntPair& operator=(const IntIntPair& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IntIntPair& default_instance();

  void Swap(IntIntPair* other);

  // implements Message ----------------------------------------------

  IntIntPair* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IntIntPair& from);
  void MergeFrom(const IntIntPair& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 first = 1;
  inline bool has_first() const;
  inline void clear_first();
  static const int kFirstFieldNumber = 1;
  inline ::google::protobuf::int32 first() const;
  inline void set_first(::google::protobuf::int32 value);

  // optional int32 second = 2;
  inline bool has_second() const;
  inline void clear_second();
  static const int kSecondFieldNumber = 2;
  inline ::google::protobuf::int32 second() const;
  inline void set_second(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:amarlon.IntIntPair)
 private:
  inline void set_has_first();
  inline void clear_has_first();
  inline void set_has_second();
  inline void clear_has_second();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 first_;
  ::google::protobuf::int32 second_;
  friend void  protobuf_AddDesc_utils_2eproto();
  friend void protobuf_AssignDesc_utils_2eproto();
  friend void protobuf_ShutdownFile_utils_2eproto();

  void InitAsDefaultInstance();
  static IntIntPair* default_instance_;
};
// ===================================================================


// ===================================================================

// IntIntPair

// optional int32 first = 1;
inline bool IntIntPair::has_first() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IntIntPair::set_has_first() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IntIntPair::clear_has_first() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IntIntPair::clear_first() {
  first_ = 0;
  clear_has_first();
}
inline ::google::protobuf::int32 IntIntPair::first() const {
  // @@protoc_insertion_point(field_get:amarlon.IntIntPair.first)
  return first_;
}
inline void IntIntPair::set_first(::google::protobuf::int32 value) {
  set_has_first();
  first_ = value;
  // @@protoc_insertion_point(field_set:amarlon.IntIntPair.first)
}

// optional int32 second = 2;
inline bool IntIntPair::has_second() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void IntIntPair::set_has_second() {
  _has_bits_[0] |= 0x00000002u;
}
inline void IntIntPair::clear_has_second() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void IntIntPair::clear_second() {
  second_ = 0;
  clear_has_second();
}
inline ::google::protobuf::int32 IntIntPair::second() const {
  // @@protoc_insertion_point(field_get:amarlon.IntIntPair.second)
  return second_;
}
inline void IntIntPair::set_second(::google::protobuf::int32 value) {
  set_has_second();
  second_ = value;
  // @@protoc_insertion_point(field_set:amarlon.IntIntPair.second)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace amarlon

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_utils_2eproto__INCLUDED
