macro(header_dirs start_dir return_list)
    file(GLOB_RECURSE new_list ${start_dir}/*.h)
        set(dir_list "")
        foreach(file_path ${new_list})
            get_filename_component(dir_path ${file_path} PATH)
            set(dir_list ${dir_list} ${dir_path})
        endforeach()
        list(REMOVE_DUPLICATES dir_list)
        set(${return_list} ${dir_list})
endmacro()